WITH MAX_PRODUCT AS (
    SELECT CATEGORY, MAX(PRICE) MAX_PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
    GROUP BY CATEGORY
)

SELECT F.CATEGORY, M.MAX_PRICE, F.PRODUCT_NAME
FROM FOOD_PRODUCT F
JOIN MAX_PRODUCT M 
    ON F.CATEGORY = M.CATEGORY
    AND F.PRICE = M.MAX_PRICE
ORDER BY MAX_PRICE DESC






# SELECT CATEGORY, PRICE, PRODUCT_NAME
# FROM FOOD_PRODUCT
# WHERE (CATEGORY, PRICE) IN (SELECT CATEGORY, MAX(PRICE)
#                            FROM FOOD_PRODUCT
#                            GROUP BY CATEGORY)
#     AND CATEGORY IN ('과자', '국', '김치', '식용유')
# ORDER BY PRICE DESC