SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE DATE_FORMAT(START_DATE, "%Y-%m") BETWEEN '2022-08' AND '2022-10' 
AND CAR_ID IN (SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                 WHERE DATE_FORMAT(START_DATE, "%Y-%m") BETWEEN '2022-08' AND '2022-10'
                 GROUP BY CAR_ID HAVING COUNT(*) >= 5)
GROUP BY MONTH(START_DATE), CAR_ID
ORDER BY MONTH, CAR_ID DESC

















# SELECT MONTH(START_DATE) MONTH, CAR_ID, COUNT(*) RECORDS
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# WHERE MONTH(START_DATE) BETWEEN 8 AND 10
#     AND CAR_ID IN (SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
#                 WHERE MONTH(START_DATE) BETWEEN 8 AND 10
#                 GROUP BY CAR_ID
#                 HAVING COUNT(*) >= 5)
# GROUP BY MONTH(START_DATE), CAR_ID
# ORDER BY MONTH, CAR_ID DESC