WITH RECURSIVE TIME AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1 AS HOUR
    FROM TIME
    WHERE HOUR < 23
)

SELECT T.HOUR, IFNULL(COUNT(A.ANIMAL_ID), 0) AS COUNT
FROM TIME T
LEFT JOIN (SELECT HOUR(DATETIME) HOUR, ANIMAL_ID
          FROM ANIMAL_OUTS) A ON T.HOUR = A.HOUR
GROUP BY T.HOUR
ORDER BY T.HOUR




# WITH RECURSIVE R AS (
#     SELECT 0 AS HOUR
#     UNION ALL
#     SELECT HOUR + 1
#     FROM R
#     WHERE HOUR < 23
# )

# SELECT R.HOUR, IFNULL(COUNT(A.ANIMAL_ID), 0) COUNT
# FROM R LEFT JOIN (SELECT HOUR(DATETIME) HOUR, ANIMAL_ID FROM ANIMAL_OUTS) A ON R.HOUR = A.HOUR
# GROUP BY R.HOUR
# ORDER BY R.HOUR