SELECT E1.ID, E1.GENOTYPE, E2.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA E1
LEFT JOIN ECOLI_DATA E2 ON E1.PARENT_ID = E2.ID
WHERE E2.GENOTYPE & E1.GENOTYPE = E2.GENOTYPE
ORDER BY E1.ID 










# SELECT E.ID, E.GENOTYPE, P.GENOTYPE AS PARENT_GENOTYPE
# FROM ECOLI_DATA E JOIN ECOLI_DATA P ON E.PARENT_ID=P.ID
# WHERE E.GENOTYPE & P.GENOTYPE = P.GENOTYPE
# ORDER BY E.ID;