WITH RECURSIVE GENERATION AS (
    SELECT ID, PARENT_ID, 1 AS GEN
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION ALL
    SELECT E.ID, E.PARENT_ID, G.GEN+1 AS GEN
    FROM ECOLI_DATA E JOIN GENERATION G
    WHERE E.PARENT_ID = G.ID
)

# SELECT *
SELECT COUNT(E1.ID) AS COUNT, G.GEN AS GENERATION
FROM ECOLI_DATA E1 
LEFT JOIN ECOLI_DATA E2 ON E1.ID = E2.PARENT_ID
LEFT JOIN GENERATION G ON E1.ID = G.ID
WHERE E2.ID IS NULL
GROUP BY G.GEN
ORDER BY G.GEN