SELECT COUNT(FI.FISH_TYPE) FISH_COUNT
FROM FISH_INFO FI
JOIN FISH_NAME_INFO FNI ON FI.FISH_TYPE = FNI.FISH_TYPE
WHERE FNI.FISH_NAME IN ('BASS', 'SNAPPER')











# SELECT COUNT(*) FISH_COUNT
# FROM FISH_INFO
# WHERE FISH_TYPE = (SELECT FISH_TYPE FROM FISH_NAME_INFO
#                    WHERE FISH_NAME = 'BASS')
#     OR FISH_TYPE = (SELECT FISH_TYPE FROM FISH_NAME_INFO
#                    WHERE FISH_NAME = 'SNAPPER')