WITH DURATION AS (
    SELECT H.HISTORY_ID, DATEDIFF(H.END_DATE, H.START_DATE)+1 AS RENT_DURATION,
        CASE
            WHEN DATEDIFF(H.END_DATE, H.START_DATE)+1 >= 90 THEN '90일 이상'
            WHEN DATEDIFF(H.END_DATE, H.START_DATE)+1 >= 30 THEN '30일 이상'
            WHEN DATEDIFF(H.END_DATE, H.START_DATE)+1 >= 7 THEN '7일 이상'
            ELSE NULL
        END AS DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
)


SELECT H.HISTORY_ID, TRUNCATE(C.DAILY_FEE * D.RENT_DURATION * (1-IFNULL(P.DISCOUNT_RATE, 0)/100), 0) AS FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
JOIN CAR_RENTAL_COMPANY_CAR C ON H.CAR_ID = C.CAR_ID
JOIN DURATION D ON H.HISTORY_ID = D.HISTORY_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P ON D.DURATION_TYPE = P.DURATION_TYPE AND C.CAR_TYPE = P.CAR_TYPE
WHERE C.CAR_TYPE = '트럭'
ORDER BY FEE DESC, HISTORY_ID DESC







# WITH HISTORY AS (
#     SELECT HISTORY_ID, CAR_ID, DATEDIFF(END_DATE, START_DATE)+1 AS DURATION,
#             CASE WHEN DATEDIFF(END_DATE, START_DATE)+1 >= 90 THEN '90일 이상'
#                  WHEN DATEDIFF(END_DATE, START_DATE)+1 >= 30 THEN '30일 이상'
#                  WHEN DATEDIFF(END_DATE, START_DATE)+1 >= 7 THEN '7일 이상'
#                  ELSE NULL END AS DURATION_TYPE
#     FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# )
# #SELECT * FROM HISTORY

# SELECT H.HISTORY_ID, TRUNCATE(C.DAILY_FEE * (1-IFNULL(P.DISCOUNT_RATE, 0)/100) * H.DURATION, 0) AS FEE
# FROM CAR_RENTAL_COMPANY_CAR C JOIN HISTORY H USING(CAR_ID) LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P ON C.CAR_TYPE = P.CAR_TYPE AND H.DURATION_TYPE = P.DURATION_TYPE
# WHERE C.CAR_TYPE = '트럭'
# ORDER BY FEE DESC, H.HISTORY_ID DESC