WITH RECURSIVE GENERATION AS (
    # 1세대
    SELECT ID, PARENT_ID, 1 AS GEN
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    # 2세대 이후
    SELECT E.ID, G.PARENT_ID, G.GEN+1 AS GEN
    FROM ECOLI_DATA E JOIN GENERATION G 
    WHERE E.PARENT_ID = G.ID
)

SELECT ID
FROM GENERATION
WHERE GEN = 3
ORDER BY ID